### ISSUE TITLE
Camera GUI don´t start the service

### ISSUE THREAD

**Issue by sm7tix** [Mo3he/Axis_Cam_ZeroTier#3]
In the camera GUI when turned on, it do not start service when checked in tty. 
Service start from tty with zerotier-one -d9993 -d & but when i close the tty the service stops again.

**Comment by Mo3he** [comment]
This has been resolved in the latest commit, please check and let me know.

**Comment by sm7tix** [comment]
I downloaded the zip file but same issue. I do not have git on my windows computer.

**Comment by sm7tix** [comment]
I cloned on my linux computer and installed on camera. Same issue. Service not running if i start from camer gui.

**Comment by Mo3he** [comment]
Please try deleting the acap, restart the camera, then install the new acap. This will just make sure there is no already running instance of the service.

**Comment by sm7tix** [comment]
Hi
Tried that now with the same result. Gui dont start but i can start in tty. 
But as soon the tty is closed Zerotier stops.
Br Stefan

Den 30 april 2023 07:26:11 skrev Weston Blieden ***@***.***>:

**Comment by Mo3he** [comment]
this time it is definitly resolved, added a wait at the end of the script, latest commit has the working eap's

**Comment by sm7tix** [comment]
Works perfect!
Thanks.

Den 30 april 2023 13:47:43 skrev Weston Blieden ***@***.***>:
